#!/usr/bin/env bash

grey(){ echo -e "\e[0;30m${@}\e[0;30m" ; }
green(){ echo -e "\e[0;32m${@}\e[0;30m" ; }
blue(){ echo -e "\e[0;34m${@}\e[0;30m" ; }

fetch_props(){
  path="./translations/wikidata/${1}.json"
  { [ -e "$path" ] && blue "wikidata $1: already fetched" ; } ||
  { grey "fetching: wikidata - $lang" && ./node_modules/.bin/wd props --lang $1 > $path && green "fetched: wikidata - $lang" & } ;
}

fetch_props 'en'

for lang in $(cat ./assets/translated_langs);
do fetch_props $lang;
done;

wait
echo 'done fetching wikidata translations'
