#!/usr/bin/env bash
set -eu

git checkout master
git push origin master
git checkout -B dist
npm run build
git add --force dist
git commit -m 'dist: updated'
git push origin --force dist
cp -r dist dist.backup
git checkout master
# Recover the ./dist directory
mv dist.backup dist
